// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProdutosApiNetCore.Data;

#nullable disable

namespace ProdutosApiNetCore.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    [Migration("20240314132040_inicial")]
    partial class inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("ProdutosApiNetCore.Entity.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescricaoItem")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PedidoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PorcentagemDescontoItem")
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantidadeItem")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ValorEconomizadoItem")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorLiquidoItem")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorTotalItem")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorUnitarioItem")
                        .HasColumnType("TEXT");

                    b.HasKey("ItemId");

                    b.HasIndex("PedidoId");

                    b.ToTable("Itens");
                });

            modelBuilder.Entity("ProdutosApiNetCore.Entity.Pedido", b =>
                {
                    b.Property<int>("PedidoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DescontoPedido")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeFornecedor")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PorcentagemDescontoClienteFidelidade")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorTotalPagar")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorTotalPedido")
                        .HasColumnType("TEXT");

                    b.HasKey("PedidoId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("ProdutosApiNetCore.Entity.Item", b =>
                {
                    b.HasOne("ProdutosApiNetCore.Entity.Pedido", null)
                        .WithMany("Itens")
                        .HasForeignKey("PedidoId");
                });

            modelBuilder.Entity("ProdutosApiNetCore.Entity.Pedido", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
